name: comoving-rv

channels:
  - astropy

dependencies:
  - python=3
  - astropy>1.3
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pillow
  - mpmath
  - sqlalchemy
  - pip:
    - six
    - ccdproc
    - pyyaml
    - astroquery
